name: CI Pipeline - IAS

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  # JOB 1: VALIDACIÓN UNITARIA, ESTÁTICA Y SEGURIDAD BASE #
  backend-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install bandit pip-audit  # Instalamos Bandit y Pip-Audit

    # CONSIGNA: Análisis con Bandit (Corre siempre para auditar tu código)
    - name: Run Bandit Security Scan
      run: |
        bandit -r app/

    # CONSIGNA: Tests de seguridad avanzados (SOLO si el PR va hacia la rama main)
    - name: Run Advanced Security Tests (pip-audit)
      if: github.base_ref == 'main'
      run: |
        pip-audit

    - name: Run Unit Tests
      env:
        PYTHONPATH: .
      run: |
        pytest tests/unit/test_main.py

  # JOB 2: VALIDACIÓN DE INTEGRACIÓN (Depende del éxito del Job 1)
  backend-integration-tests:
    runs-on: ubuntu-latest
    needs: backend-unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Integration Tests
      env:
        PYTHONPATH: .
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        pytest tests/integration/test_integration.py